language: php
php:
  - 5.4
  - 5.5

branches:
  only:
    - /^(?i:v).*$/

before_script:
  - composer self-update
  - composer install
  - test/phpunit.phar --self-update


script:
  - test/phpunit.phar -c test/phpunit.xml --coverage-clover=test/coverage.xml

before_install:
  - pip install --user codecov

after_success:
  - codecov --root test
