language: php
php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install
#  - pip install --upgrade pip
#  - pip install --user codecov

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
