language: php
php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install
  - test/phpunit.phar --self-update


script:
  - test/phpunit.phar --coverage-clover=coverage.xml

before_install:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
